#!/bin/bash


# stop execution if an error or undefined variable is encountered
set -eu


run_as_root()
{
    if [ $EUID != "0" ]; then
        sudo "$0" "$@"
        exit $?
    fi
}

# ensure we're running as root
run_as_root


# install, configure, and start elasticsearch
yum install -y java-1.8.0-openjdk-headless
rpm -ivh https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.1.rpm
sed -i -e '/^#cluster.name:/s/^#cluster.name:.*/cluster.name: dev0/' /etc/elasticsearch/elasticsearch.yml
sed -i -e '/^#node.name:/s/^#node.name:.*/node.name: vagrant0/' /etc/elasticsearch/elasticsearch.yml
systemctl daemon-reload
systemctl start elasticsearch.service
systemctl enable elasticsearch.service
